name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4.1.2
      - name: Autenticação Docker
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Construção da imagem docker
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            brunods85/devops4devs-news:latest
            brunods85/devops4devs-news:${{github.run_number}}
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4.1.2
      - name: Configuração ambiente AWS
        uses: aws-actions/configure-aws-credentials@4
        with:
          aws-region: "us-east-1"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
      - name: Configuração kubeconfig
        run: echo "aws eks update kubeconfig --name devops4devs-eks"
      - name: Executar o deploy
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            ./k8s/deploy.yaml
          images: |
            brunods85/devops4devs-news:${{github.run_number}}
