name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
        name: Checkout do repositório
      - name: Autenticação Docker
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Construção da imagem docker
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            brunods85/devops4devs-news:latest
            brunods85/devops4devs-news:${{github.run_number}}
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Conectar com o Kubernetes
        run: echo "Configuração do kubeconfig"
      - name: Executar o deploy
        run: echo "kubectl apply"
